name: CharmedChars
version: ${version}
main: org.stephanosbad.charmedChars.CharmedChars
api-version: '1.21'
load: STARTUP
authors: [ StephanosBad ]
description: Closed Java Spigot plugin for Minecraft Java Edition
commands:
  charmedChars:
    usage: /charmedChars <player> <string>
    description: Give a string of letter or number blocks to a player.
  charblock:
    usage: /charblock <player> <color> <text>
    description: Give custom character blocks to a player.
    permission: charmedChars.blocks
  example:
    description: An example command
    usage: /example [player]
    permission: charmedChars.example
    aliases: [ex, demo]
  reload:
    description: Reload the plugin configuration
    usage: /charmedChars reload
    permission: charmedChars.admin
  textures:
    description: Manage custom textures and resource packs
    usage: /textures <download|status|regenerate|help>
    permission: charmedChars.textures
    aliases: [resourcepack, rp, pack]
  debugitem:
    description: Debug item in main hand (shows custom model data)
    usage: /debugitem
    permission: charmedChars.admin
    aliases: [itemdebug, checkitem]

permissions:
  charmedChars.blocks:
    description: Allows giving character blocks to players
    default: op
  charmedChars.example:
    description: Allows use of the example command
    default: op
  charmedChars.admin:
    description: Admin permissions for the plugin
    default: op
  charmedChars.textures:
    description: Allows downloading custom textures
    default: true
  charmedChars.*:
    description: Gives access to all MyPlugin permissions
    children:
      charmedChars.blocks: true
      charmedChars.example: true
      charmedChars.admin: true
      charmedChars.textures: true
    default: op
