name: CharmedChars
version: '1.0-SNAPSHOT'
main: org.stephanosbad.charmedChars.CharmedChars
api-version: '1.21.6'
load: STARTUP
authors: [ Stephy Badbaby ]
description: Closed Java Spigot plugin for Minecraft Java Edition (18+)
depend: [ Oraxen ]
softdepend: [ WorldGuard, GriefPrevention ]
commands:
  charblock:
    usage: /charblock <player> <string>
    description: Give a string of letter or number blocks to a player.
